const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('static/app.js', 'utf8');
const start = source.indexOf('function transactionBadges(');
const end = source.indexOf('const overviewStyle=', start);
const context = {badgeDefinitions: [], esc: s => String(s).replaceAll('<', '&lt;')};
vm.createContext(context);
vm.runInContext(source.slice(start, end), context);
context.badgeDefinitions = [{name:'EMI', patterns:['emi'], whole_word:1}];
assert.match(context.transactionBadges({description:'EMI 123'}), /EMI/);
assert.equal(context.transactionBadges({description:'PREMIUM PAYMENT'}), '');
context.badgeDefinitions = [{name:'Subscription', patterns:['netflix','spotify'], whole_word:0}];
assert.match(context.transactionBadges({description:'UPI-NETFLIX LTD'}), /Subscription/);
context.badgeDefinitions = [{name:'Literal', patterns:['a+b'], whole_word:1}];
assert.match(context.transactionBadges({description:'paid a+b today'}), /Literal/);
assert.equal(context.transactionBadges({description:'paid aaab today'}), '');
context.badgeDefinitions = [];
assert.equal(context.transactionBadges({description:'EMI UPI'}), '');
console.log('Badge matching checks passed.');
