const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const source=fs.readFileSync('static/gmail.js','utf8');
const context={};vm.createContext(context);
vm.runInContext(source.slice(0,source.indexOf('(() => {')),context);
const item={filename:'statement.pdf',status:'imported',sender:'cards@bank.example',subject:'September statement'};
assert.equal(context.canCreateStatementRule(item),true);
assert.equal(context.canCreateStatementRule({...item,status:'pending'}),true);
assert.equal(context.canCreateStatementRule({...item,status:'dismissed'}),false);
assert.equal(context.canCreateStatementRule({...item,filename:''}),false);
let draft=context.statementRuleDraft(item,null,null);
assert.equal(draft.sender,item.sender);assert.equal(draft.account_id,'');assert.equal(draft.password_account_id,'');assert.equal(draft.subject_keyword,'statement');
draft=context.statementRuleDraft({...item,routing:{account_id:3,password_account_id:4}},null,null);
assert.equal(draft.account_id,3);assert.equal(draft.password_account_id,4);
draft=context.statementRuleDraft({...item,routing:{ambiguous:true,account_id:3}},null,null);
assert.equal(draft.account_id,'');
draft=context.statementRuleDraft(item,{value:'5'},{value:''});
assert.equal(draft.account_id,'5');assert.equal(draft.password_account_id,'');
draft=context.statementRuleDraft({...item,routing:{id:7,name:'Existing HDFC',sender:item.sender,subject_keyword:'monthly statement',filename_keyword:'.pdf',account_id:3,password_account_id:3}},null,null);
assert.equal(draft.id,7);assert.equal(draft.name,'Existing HDFC');assert.equal(draft.subject_keyword,'monthly statement');assert.equal(draft.filename_keyword,'.pdf');
console.log('Pending/imported statement rule draft checks passed.');
