const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('static/app.js','utf8');
const fields=Object.fromEntries(['searchScope','globalSearch','accountFilter','transactionMonth','transactionStart','transactionEnd','categoryFilter','searchCount','transactionsBody'].map(id=>[id,{value:'',textContent:'',innerHTML:''}]));
fields.searchScope.value='current';fields.transactionStart.value='2026-08-31';fields.transactionEnd.value='2026-09-24';fields.categoryFilter.value='7';
const dates=['2026-08-30','2026-08-31','2026-09-24','2026-09-25'];
const context={$:id=>fields[id],state:{transactions:dates.map((date,i)=>({id:i+1,date,status:'active',category_id:7,amount:i===2?10:-10,description:'Entry'+i,account_name:'Bank'})),review:[],trash:[]},matchesSearch:()=>true,esc:String,fmt:String,typeLabel:()=>'',transactionDescription:t=>t.description,matchingBadges:t=>t.id===2?[{id:9}]:[]};
context.transactionDate=String;
context.transactionDateCell=t=>t.date;
context.compareTransactionOrder=(a,b)=>b.date.localeCompare(a.date)||((b.sort_seconds??-1)-(a.sort_seconds??-1))||b.id-a.id;
vm.createContext(context);vm.runInContext(source.slice(source.indexOf('function renderTransactions(){'),source.indexOf("$('transactions').querySelector('.toolbar')")),context);
context.renderTransactions();
assert.equal(fields.searchCount.textContent,'2 matching transactions');
assert.ok(fields.transactionsBody.innerHTML.includes('Entry1'));assert.ok(fields.transactionsBody.innerHTML.includes('Entry2'));
assert.ok(!fields.transactionsBody.innerHTML.includes('Entry0'));assert.ok(!fields.transactionsBody.innerHTML.includes('Entry3'));
assert.ok(fields.transactionsBody.innerHTML.includes('amount income'));assert.ok(fields.transactionsBody.innerHTML.includes('amount expense'));
fields.transactionStart.value='';fields.transactionEnd.value='';context.renderTransactions();assert.equal(fields.searchCount.textContent,'4 matching transactions');
fields.transactionMonth.value='2026-08';context.renderTransactions();assert.equal(fields.searchCount.textContent,'2 matching transactions');
fields.transactionMonth.value='';fields.badgeFilter={value:'9'};context.renderTransactions();assert.equal(fields.searchCount.textContent,'1 matching transaction');assert.ok(fields.transactionsBody.innerHTML.includes('Entry1'));
fields.badgeFilter.value='';context.renderTransactions();assert.equal(fields.searchCount.textContent,'4 matching transactions');
console.log('Date ranges, badge filtering, reset and debit/credit markup checks passed.');
